/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminModuleDto } from './adminModuleDto';
import { ApiError } from './apiError';


export interface AdminModuleDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AdminModuleDto;
    error?: ApiError;
}

