/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { AdminUserListItemDto } from './adminUserListItemDto';


export interface AdminUserListItemDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AdminUserListItemDto;
    error?: ApiError;
}

