/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminStudentAttendanceRowDto { 
    studentId?: string;
    userId?: string;
    studentNumber?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    expectedSessionsTotal?: number;
    attendedSessionsTotal?: number;
    overallPercent?: number | null;
}

