/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCourseDto } from './adminCourseDto';
import { ApiError } from './apiError';


export interface AdminCourseDtoIReadOnlyListApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: Array<AdminCourseDto> | null;
    error?: ApiError;
}

