/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminUserDetailDto } from './adminUserDetailDto';
import { ApiError } from './apiError';


export interface AdminUserDetailDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AdminUserDetailDto;
    error?: ApiError;
}

