/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminStudentAttendanceRowDto } from './adminStudentAttendanceRowDto';


export interface AdminStudentAttendanceRowDtoPagedDto { 
    items?: Array<AdminStudentAttendanceRowDto> | null;
    page?: number;
    pageSize?: number;
    total?: number;
}

