/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { AdminStudentAttendanceRowDtoPagedDto } from './adminStudentAttendanceRowDtoPagedDto';


export interface AdminStudentAttendanceRowDtoPagedDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AdminStudentAttendanceRowDtoPagedDto;
    error?: ApiError;
}

