/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminCourseDetailDto } from './adminCourseDetailDto';
import { ApiError } from './apiError';


export interface AdminCourseDetailDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AdminCourseDetailDto;
    error?: ApiError;
}

