/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssessmentGradeDto } from './assessmentGradeDto';
import { ApiError } from './apiError';


export interface AssessmentGradeDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AssessmentGradeDto;
    error?: ApiError;
}

