/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttendanceSettingsDto } from './attendanceSettingsDto';
import { ApiError } from './apiError';


export interface AttendanceSettingsDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AttendanceSettingsDto;
    error?: ApiError;
}

