/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditEventDto { 
    id?: string;
    occurredAtUtc?: string;
    actorUserId?: string | null;
    action?: string | null;
    entityType?: string | null;
    entityId?: string | null;
    summary?: string | null;
    changesJson?: string | null;
    metadataJson?: string | null;
}

