/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditEventDto } from './auditEventDto';
import { ApiError } from './apiError';


export interface AuditEventDtoIReadOnlyListApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: Array<AuditEventDto> | null;
    error?: ApiError;
}

