/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResultDto { 
    userId?: string;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    permissions?: number;
    accessToken?: string | null;
}

