/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthResultDto } from './authResultDto';
import { ApiError } from './apiError';


export interface AuthResultDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: AuthResultDto;
    error?: ApiError;
}

