/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessageDto } from './chatMessageDto';
import { ApiError } from './apiError';


export interface ChatMessageDtoListApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: Array<ChatMessageDto> | null;
    error?: ApiError;
}

