/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseEnrollmentStatus } from './courseEnrollmentStatus';


export interface CourseEnrollmentDto { 
    courseId?: string;
    courseCode?: string | null;
    title?: string | null;
    academicYear?: number;
    yearOfStudy?: number;
    semester?: number;
    status?: CourseEnrollmentStatus;
}
export namespace CourseEnrollmentDto {
}


