/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { CourseEnrollmentRowDto } from './courseEnrollmentRowDto';


export interface CourseEnrollmentRowDtoIReadOnlyListApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: Array<CourseEnrollmentRowDto> | null;
    error?: ApiError;
}

