/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentListItemDto } from './studentListItemDto';
import { CourseEnrollmentStatus } from './courseEnrollmentStatus';


export interface CourseEnrollmentRowDto { 
    student?: StudentListItemDto;
    courseEnrollmentId?: string;
    status?: CourseEnrollmentStatus;
    academicYear?: number;
    yearOfStudy?: number;
    semester?: number;
    startDateUtc?: string;
    endDateUtc?: string | null;
}
export namespace CourseEnrollmentRowDto {
}


