/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const CourseEnrollmentStatus = {
    NUMBER_1: 1
} as const;
export type CourseEnrollmentStatus = typeof CourseEnrollmentStatus[keyof typeof CourseEnrollmentStatus];

