/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateThreadResponse } from './createThreadResponse';
import { ApiError } from './apiError';


export interface CreateThreadResponseApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: CreateThreadResponse;
    error?: ApiError;
}

