/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleEnrollmentStatus } from './moduleEnrollmentStatus';


export interface ModuleCardDto { 
    moduleId?: string;
    moduleCode?: string | null;
    title?: string | null;
    academicYear?: number;
    yearOfStudy?: number;
    semester?: number;
    status?: ModuleEnrollmentStatus;
}
export namespace ModuleCardDto {
}


