/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleEnrollmentStatus } from './moduleEnrollmentStatus';
import { StudentListItemDto } from './studentListItemDto';


export interface ModuleEnrollmentRowDto { 
    student?: StudentListItemDto;
    moduleEnrollmentId?: string;
    status?: ModuleEnrollmentStatus;
    academicYear?: number;
    yearOfStudy?: number;
    semester?: number;
    enrolledAtUtc?: string;
    completedAtUtc?: string | null;
}
export namespace ModuleEnrollmentRowDto {
}


