/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleElementDto } from './moduleElementDto';
import { ApiError } from './apiError';


export interface ModuleElementDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: ModuleElementDto;
    error?: ApiError;
}

