/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { ModuleCardDto } from './moduleCardDto';


export interface ModuleCardDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: ModuleCardDto;
    error?: ApiError;
}

