/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleFileExistsDto } from './moduleFileExistsDto';
import { ApiError } from './apiError';


export interface ModuleFileExistsDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: ModuleFileExistsDto;
    error?: ApiError;
}

