/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleFileDto } from './moduleFileDto';
import { ApiError } from './apiError';


export interface ModuleFileDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: ModuleFileDto;
    error?: ApiError;
}

