/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyAttendanceDayDto } from './myAttendanceDayDto';


export interface MyAttendanceDayDtoPagedDto { 
    items?: Array<MyAttendanceDayDto> | null;
    page?: number;
    pageSize?: number;
    total?: number;
}

