/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyAttendanceDayModuleDto } from './myAttendanceDayModuleDto';


export interface MyAttendanceDayDto { 
    date?: string;
    attendedModulesCount?: number;
    modules?: Array<MyAttendanceDayModuleDto> | null;
}

