/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyAttendanceOverviewDto } from './myAttendanceOverviewDto';
import { MyAttendanceDayDtoPagedDto } from './myAttendanceDayDtoPagedDto';


export interface MyAttendanceResponseDto { 
    overview?: MyAttendanceOverviewDto;
    days?: MyAttendanceDayDtoPagedDto;
}

