/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyAttendanceResponseDto } from './myAttendanceResponseDto';
import { ApiError } from './apiError';


export interface MyAttendanceResponseDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: MyAttendanceResponseDto;
    error?: ApiError;
}

