/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyModuleAttendanceSummaryDto } from './myModuleAttendanceSummaryDto';


export interface MyAttendanceOverviewDto { 
    from?: string;
    to?: string;
    expectedSessionsTotal?: number;
    attendedSessionsTotal?: number;
    overallPercent?: number | null;
    perModule?: Array<MyModuleAttendanceSummaryDto> | null;
}

