/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MyAttendanceDayModuleDto { 
    moduleId?: string;
    moduleName?: string | null;
    isAttended?: boolean;
    checkedInAtUtc?: string | null;
    scheduledStartLocal?: string;
    scheduledEndLocal?: string;
}

