/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DayOfWeek } from './dayOfWeek';


export interface MyModuleAttendanceSummaryDto { 
    moduleId?: string;
    moduleName?: string | null;
    scheduledDay?: DayOfWeek;
    runsFrom?: string;
    runsTo?: string;
    expectedSessions?: number;
    attendedSessions?: number;
    attendancePercent?: number | null;
}
export namespace MyModuleAttendanceSummaryDto {
}


