/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionMetadataDto { 
    key?: string | null;
    bit?: number;
    value?: number;
    description?: string | null;
}

