/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { PermissionMetadataDto } from './permissionMetadataDto';


export interface PermissionMetadataDtoIReadOnlyListApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: Array<PermissionMetadataDto> | null;
    error?: ApiError;
}

