/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RagSourceDto { 
    sourceType?: string | null;
    moduleElementId?: string | null;
    moduleFileId?: string | null;
    title?: string | null;
    pageNumber?: number | null;
    snippet?: string | null;
}

