/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Role { 
    id?: string;
    createdAtUtc?: string;
    createdByUserId?: string | null;
    updatedAtUtc?: string | null;
    updatedByUserId?: string | null;
    isDeleted?: boolean;
    deletedAtUtc?: string | null;
    deletedByUserId?: string | null;
    key?: string | null;
    name?: string | null;
    permissions?: number;
    rank?: number;
    isSystem?: boolean;
}

