/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';
import { ApiError } from './apiError';


export interface RoleDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: RoleDto;
    error?: ApiError;
}

