/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RagSourceDto } from './ragSourceDto';


export interface SendMessageResponse { 
    assistantMessageId?: string;
    answer?: string | null;
    sources?: Array<RagSourceDto> | null;
    highlightElementId?: string | null;
}

