/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SendMessageResponse } from './sendMessageResponse';
import { ApiError } from './apiError';


export interface SendMessageResponseApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: SendMessageResponse;
    error?: ApiError;
}

