/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseEnrollmentStatus } from './courseEnrollmentStatus';


export interface SetCourseEnrollmentStatusDto { 
    status?: CourseEnrollmentStatus;
}
export namespace SetCourseEnrollmentStatusDto {
}


