/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleEnrollmentStatus } from './moduleEnrollmentStatus';


export interface SetModuleEnrollmentStatusDto { 
    status?: ModuleEnrollmentStatus;
}
export namespace SetModuleEnrollmentStatusDto {
}


