/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StaffModuleCardDto { 
    moduleId?: string;
    moduleCode?: string | null;
    title?: string | null;
    staffRole?: string | null;
}

