/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { StaffDashboardDto } from './staffDashboardDto';


export interface StaffDashboardDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: StaffDashboardDto;
    error?: ApiError;
}

