/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseEnrollmentStatus } from './courseEnrollmentStatus';


export interface StudentCourseHistoryRowDto { 
    enrollmentId?: string;
    courseId?: string;
    courseCode?: string | null;
    title?: string | null;
    status?: CourseEnrollmentStatus;
    academicYear?: number;
    yearOfStudy?: number;
    semester?: number;
    startDateUtc?: string;
    endDateUtc?: string | null;
}
export namespace StudentCourseHistoryRowDto {
}


