/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiError } from './apiError';
import { StudentEnrollmentHistoryDto } from './studentEnrollmentHistoryDto';


export interface StudentEnrollmentHistoryDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: StudentEnrollmentHistoryDto;
    error?: ApiError;
}

