/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentAssessmentGradeDto { 
    assessmentElementId?: string;
    weight?: number;
    marksPublished?: boolean;
    gradeId?: string;
    grade?: number;
    feedback?: string | null;
    gradedAtUtc?: string;
}

