/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentGradesDto } from './studentGradesDto';
import { ApiError } from './apiError';


export interface StudentGradesDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: StudentGradesDto;
    error?: ApiError;
}

