/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseEnrollmentDto } from './courseEnrollmentDto';
import { ModuleCardDto } from './moduleCardDto';


export interface StudentDashboardDto { 
    enrolledCourse?: CourseEnrollmentDto;
    currentModules?: Array<ModuleCardDto> | null;
    pastModules?: Array<ModuleCardDto> | null;
}

