/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentCourseGradesDto } from './studentCourseGradesDto';


export interface StudentGradesDto { 
    courses?: Array<StudentCourseGradesDto> | null;
}

