/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentAssessmentGradeDto } from './studentAssessmentGradeDto';


export interface StudentModuleGradesDto { 
    moduleId?: string;
    moduleCode?: string | null;
    title?: string | null;
    academicYear?: number;
    credits?: number | null;
    level?: number | null;
    marksPublished?: boolean;
    assessments?: Array<StudentAssessmentGradeDto> | null;
}

