/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentCourseHistoryRowDto } from './studentCourseHistoryRowDto';
import { StudentModuleHistoryRowDto } from './studentModuleHistoryRowDto';


export interface StudentEnrollmentHistoryDto { 
    studentId?: string;
    userId?: string;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    studentNumber?: string | null;
    courses?: Array<StudentCourseHistoryRowDto> | null;
    modules?: Array<StudentModuleHistoryRowDto> | null;
}

