/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleEnrollmentStatus } from './moduleEnrollmentStatus';


export interface StudentModuleHistoryRowDto { 
    enrollmentId?: string;
    moduleId?: string;
    moduleCode?: string | null;
    title?: string | null;
    status?: ModuleEnrollmentStatus;
    academicYear?: number;
    yearOfStudy?: number;
    semester?: number;
    enrolledAtUtc?: string;
    completedAtUtc?: string | null;
}
export namespace StudentModuleHistoryRowDto {
}


