/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentDashboardDto } from './studentDashboardDto';
import { ApiError } from './apiError';


export interface StudentDashboardDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: StudentDashboardDto;
    error?: ApiError;
}

