/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentModuleGradesDto } from './studentModuleGradesDto';


export interface StudentCourseGradesDto { 
    courseId?: string;
    courseCode?: string | null;
    title?: string | null;
    description?: string | null;
    award?: string | null;
    modules?: Array<StudentModuleGradesDto> | null;
}

