/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDetailDto } from './userDetailDto';
import { ApiError } from './apiError';


export interface UserDetailDtoApiResponse { 
    success?: boolean;
    statusCode?: number;
    data?: UserDetailDto;
    error?: ApiError;
}

