export * from './adminAttendance.service';
import { AdminAttendanceService } from './adminAttendance.service';
export * from './adminAudit.service';
import { AdminAuditService } from './adminAudit.service';
export * from './adminBulkUser.service';
import { AdminBulkUserService } from './adminBulkUser.service';
export * from './adminCatalog.service';
import { AdminCatalogService } from './adminCatalog.service';
export * from './adminEnrollment.service';
import { AdminEnrollmentService } from './adminEnrollment.service';
export * from './adminUser.service';
import { AdminUserService } from './adminUser.service';
export * from './attendance.service';
import { AttendanceService } from './attendance.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './enrollmentQueries.service';
import { EnrollmentQueriesService } from './enrollmentQueries.service';
export * from './enrollments.service';
import { EnrollmentsService } from './enrollments.service';
export * from './me.service';
import { MeService } from './me.service';
export * from './module.service';
import { ModuleService } from './module.service';
export * from './moduleChat.service';
import { ModuleChatService } from './moduleChat.service';
export * from './moduleFiles.service';
import { ModuleFilesService } from './moduleFiles.service';
export * from './moduleRag.service';
import { ModuleRagService } from './moduleRag.service';
export * from './permission.service';
import { PermissionService } from './permission.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdminAttendanceService, AdminAuditService, AdminBulkUserService, AdminCatalogService, AdminEnrollmentService, AdminUserService, AttendanceService, AuthService, EnrollmentQueriesService, EnrollmentsService, MeService, ModuleService, ModuleChatService, ModuleFilesService, ModuleRagService, PermissionService, RoleService, UserService];
